spring.application.name=identity-service
server.port=8082

spring.datasource.url=${IDENTITY_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
spring.flyway.enabled=true

identity.jwt.private-key=${IDENTITY_JWT_PRIVATE_KEY}
identity.jwt.public-key=${IDENTITY_JWT_PUBLIC_KEY}
identity.jwt.issuer=${IDENTITY_JWT_ISSUER:http://localhost:8082}
identity.jwt.access-token-ttl=${IDENTITY_JWT_ACCESS_TOKEN_TTL:PT15M}
